services:
  postgres:
    image: postgres:16-alpine
    container_name: voyager-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: voyager
      POSTGRES_PASSWORD: voyager_dev
      POSTGRES_DB: voyager
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: voyager-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
